name: Pull Request Checks

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  # Quick checks for PRs
  pr-checks:
    name: PR Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript check
        run: npx tsc --noEmit

      - name: ESLint check
        run: npx eslint . --ext .js,.jsx,.ts,.tsx --max-warnings 0

      - name: Check for security vulnerabilities
        run: npm audit --audit-level=high

      - name: Validate Expo config
        run: npx expo-doctor

  # Build preview (optional)
  build-preview:
    name: Build Preview
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install EAS CLI
        run: npm install -g @expo/eas-cli

      - name: Login to Expo
        run: |
          echo ${{ secrets.EXPO_TOKEN }} | eas login --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build preview
        run: eas build --platform android --profile preview --non-interactive 